; Inno Setup Script for LicenseFlow Manager
; Generated by Antigravity (Google DeepMind Advanced Agentic Coding Team)
; High-Integrity Windows Installation Package

[Setup]
AppId={{E57D5C5A-BF9E-4E9B-BD41-86EF2E4C4B5E}}
AppName=LicenseFlow Manager
AppVersion=1.2.9
AppPublisher=ezPrintWork
AppPublisherURL=https://ez-hub.kr/
AppSupportURL=https://ez-hub.kr/
AppUpdatesURL=https://ez-hub.kr/
DefaultDirName={localappdata}\LicenseFlow_Manager
DisableDirPage=no
DisableProgramGroupPage=yes
OutputDir=dist
OutputBaseFilename=LicenseFlow_Manager_Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
DefaultGroupName=LicenseFlow Manager
AllowNoIcons=yes
; 제어판에 표시될 제거 관련 메타데이터
UninstallDisplayIcon={app}\LicenseFlow_Manager.exe
UninstallDisplayName=LicenseFlow Manager (이즈프린트워크 라이선스 관리자)
VersionInfoVersion=1.2.9.0
VersionInfoProductVersion=1.2.9
VersionInfoProductName=LicenseFlow Manager
VersionInfoCompany=ezPrintWork
VersionInfoDescription=LicenseFlow Manager (이즈프린트워크 라이선스 관리자)

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\LicenseFlow_Manager.exe"; DestDir: "{app}"; Flags: ignoreversion restartreplace

[Icons]
Name: "{group}\LicenseFlow Manager"; Filename: "{app}\LicenseFlow_Manager.exe"
Name: "{autodesktop}\LicenseFlow Manager"; Filename: "{app}\LicenseFlow_Manager.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\LicenseFlow_Manager.exe"; Description: "{cm:LaunchProgram,LicenseFlow Manager}"; Flags: nowait postinstall skipifsilent

[Code]
// [Safe-Upgrade 가드 장치]
// 설치를 시작하기 전, 구버전 LicenseFlow_Manager.exe가 실행 중인지 감지하여
// 백그라운드에서 강제로 프로세스를 안전하게 종료시킴으로써 파일 잠김(Write Lock) 에러를 100% 예방하고 클린 덮어쓰기를 보장합니다.
function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  
  // 숨김 모드로 taskkill 명령어를 실행하여 구버전 프로세스 종료 처리
  Exec('taskkill.exe', '/F /IM LicenseFlow_Manager.exe /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  
  // 잠시 프로세스가 완전히 정리될 수 있도록 대기 지연(0.5초) 적용
  Sleep(500);
end;
